<?php

/**
 * Implements hook_theme().
 */
function thanks_theme($existing, $type, $theme, $path) {
  return [
    'dummy_example_first' => [
      'variables' => [],
    ],
    'test' => [
      'render element' => 'element'
    ],
    'student_registration_form' => [
      'render element' => 'form'
    ]
  ];
}
/**
 * Implements template_preprocess_HOOK().
 * Обработчик переменных для первого примера.
 */
function template_preprocess_dummy_example_first(&$variables) {
  $date_formatter = \Drupal::service('date.formatter');
  $variables['date'] = $date_formatter->format(time());
}
function thanks_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  if ($form_id == 'student_registration_form') {
    $form['name']['#theme'] = 'test';
    $form['#theme'] = 'student_registration_form';
  }
}

